[project]
name = "sqlhelper-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlglot[rs]>=27.7.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
