class KeyWords:
    keywords = [
        "SELECT",
        "INSERT",
        "DELETE",
        "UPDATE",
        "UPSERT",
        "REPLACE",
        "DROP",
        "CREATE",
        "ALTER",
        "TRUNCATE",
        "WHERE",
        "FROM",
        "INNER",
        "JOIN",
        "AND",
        "ON",
        "OR",
        "LIKE",
        "IN",
        "SET",
        "BY",
        "GROUP",
        "ORDER",
        "LEFT",
        "OUTER",
        "FULL",
        "RIGHT",
        "IF",
        "END",
        "THEN",
        "AS",
        "ELSE",
        "CASE",
        "WHEN",
        "DISTINCT",
        "OVERWRITE",
        "TABLE",
        "OVER",
        "INTO",
        "VIEW",
        "NOT",
        "EXISTS",
        "EXTERNAL",
        "WITH",
        "DATABASE",
        "TEMPORARY",
        "MERGE",
    ]

    insert_keywords = [
        "INSERT",
        "CREATE",
    ]

    from_keywords = [
        "FROM",
        "JOIN",
    ]

    table_function_keywords = ["UNNEST", "LATERAL", "GENERATE_SERIES", "SEQUENCE"]
